### ISSUE TITLE
Line numbers in the Request editor

### ISSUE THREAD

**Issue by reynolds047** [MscrmTools/MscrmTools.FetchXmlTester#1]
Hello, 

I feel it would be very useful if there was an option to turn on line numbers inside of the Request editor. With errors providing a line number pointing to the problem, it would be nice to just scroll to that line, rather than the alternatives: copy/pasting to another editor with line numbers, or counting the lines manually.

**Comment by MscrmTools** [comment]
Thanks for the feature request 

Nevertheless, I’m not sure I will update this tool. FetchXmlBuilder is the tool to use when working with FerchXml
