### ISSUE TITLE
Please update use of ExecuteFetchRequest to RetrieveMultiple

### ISSUE THREAD

**Issue by MattB-msft** [MscrmTools/MscrmTools.FetchXmlTester#2]
[ExecuteFetchRequest](https://github.com/MscrmTools/MscrmTools.FetchXmlTester/blob/94eb7cec12340ad0a3e96050dd7a4df934aa6040/MsCrmTools.FetchXmlTester/FetchXmlTester.cs#L72) is a deprecated message type in the Dataverse System and is not being supported with updates to the retrievers when assets are moved around. 

Please update this to use RetrieveMultiple with a FetchXmlQuery expression. 

See [ExecuteFetchRequest](https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.executefetchrequest?view=dataverse-sdk-latest) for the deprecated message. 

thanks!

**Comment by MscrmTools** [comment]
Sure! This tool is not supposed to be used anymore since fetch xml builder is far way better
But even if I remove it from the library, users can still use it.
Anyway, I will update it

**Comment by MattB-msft** [comment]
Thanks I appreciate it,  in our experience, Folks prefer to use this tool to cross check or hand generate fetchXML

**Comment by MscrmTools** [comment]
@MattB-msft new version should be released very soon
