### ISSUE TITLE
Microsoft.Xrm.Sdk.AliasedValue in Results

### ISSUE THREAD

**Issue by chuckokerstrom** [MscrmTools/MscrmTools.FetchXmlTester#3]
Love the new grid results display, but most linked (related) results show as "Microsoft.Xrm.Sdk.AliasedValue".  This wasn't the case with the older version.  Is there a way around this?

This is a straight forward, non-aggregate query.

Thx,

Chuck
![fetchtester](https://user-images.githubusercontent.com/36867223/164283930-c6cd96aa-083b-4d58-8327-e4d6fe4c68a4.png)
![fetchtest_query](https://user-images.githubusercontent.com/36867223/164284236-3cb01c3b-aeab-48e8-a57f-2b63151861fc.png)

**Comment by MscrmTools** [comment]
I forgot this one... I will fix it very soon

**Comment by MscrmTools** [comment]
Fixed. Just wait few hours so the new version is released on XrmToolBox library

**Comment by chuckokerstrom** [comment]
Perfect!  That worked!


Regards,


Chuck
