### ISSUE TITLE
No results and grey window after update

### ISSUE THREAD

**Issue by lauraMhg** [MscrmTools/MscrmTools.FetchXmlTester#4]
Last updates made the plugin crash. As a result when executing a query no results are shown, just a grey window.

**Comment by MscrmTools** [comment]
A grey window means no result were returned. I should maybe add an explicit message when no rows are returned

**Comment by lauraMhg** [comment]
> A grey window means no result were returned. I should maybe add an explicit message when no rows are returned

I think it showed the number before the update, bad luck I tried first with a no result query... Thanks!
